### ISSUE TITLE
How i can add pieces from outside the board ?

### ISSUE THREAD

**Issue by sasukeuchihadangerous** [Clariity/react-chessboard#115]

**Comment by Manukyanq** [comment]
HI! Have you seen https://github.com/Clariity/react-chessboard/pull/88? Despite this pull request is on pause, generally the code works fine. The approach of this feature still needs to be reviewed and reconsidered, since we want to make it maximum easy and flexible for the developers. I can make it either easy in use without any styles customisation or complex in use with opportunity of styles customisation...

**Comment by sasukeuchihadangerous** [comment]
> HI! Have you seen #88? Despite this pull request is on pause, generally the code works fine. The approach of this feature still needs to be reviewed and reconsidered, since we want to make it maximum easy and flexible for the developers. I can make it either easy in use without any styles customisation or complex in use with opportunity of styles customisation...

Yes, i see it, but does your version support colored arrows and custom chess piece view depending on coordinates ? I need to make it so that I can drag and drop my custom chess piece on the board - the star piece.

**Comment by Clariity** [comment]
Closing as will be resolved by #88
