### ISSUE TITLE
No moves are available with custom positions

### ISSUE THREAD

**Issue by hoannguyen02** [Clariity/react-chessboard#132]
Hi team, 

May I ask question describe bellow?

I initial board with 2 custom positions: 
{
a7: "wP"
b8: "bP"
}

then click on position a7, there is no move available if we call `game.moves()` or  game.moves({verbose: true})

<img width="1422" alt="image" src="https://github.com/Clariity/react-chessboard/assets/16915274/98cde278-a6c7-4b8e-9d01-d67ff6dc6c8d">

Am using these dependencies:
    "chess.js": "^1.0.0-beta.7",
    "next": "14.1.0",
    "react": "^18",
    "react-chessboard": "^4.4.0",
    "react-dom": "^18",

Is there any way / example code if we can make move with custom position?

Thank you very much.

**Comment by Manukyanq** [comment]
Hi, `react-chessboard` package is UI library only and does not take responsibility for chess logic and move validation. 

You use `chess.js` library which  strictly uses classical chess game rules and in classical chess game `{ a7: "wP", b8: "bP"}` is illegal chess position, because in classical chess game black pawns start from 7th line and can move only forward to the 1st line.

try to check first is your position valid  or not with [game.validateFen(fen)](https://github.com/jhlywa/chess.js/blob/master/README.md#validatefenfen)

In my opinion its better to open issue in [chess.js](https://github.com/jhlywa/chess.js/issues) issues section. Hope I've helped you.

**Comment by hoannguyen02** [comment]
Hi @Manukyanq 

Many thanks response. 

I saw with `position` prop we have a `BoardPosition` type. May I ask how we can use it (could you show example code). At the moment I make an example like the screenshot bellow with an expectation that the king can move & capture the black rook but there is no move available.
<img width="1236" alt="image" src="https://github.com/Clariity/react-chessboard/assets/16915274/3bd0b154-e1f2-4ddf-906a-c235997070da">
<img width="395" alt="image" src="https://github.com/Clariity/react-chessboard/assets/16915274/d536922a-3db2-4db8-875a-1dee1e6f0a3d">

My idea is render some custom positions to the board and play around but  don't know how to do that. For now I can only using `game.fen()` for `position` prop.

Thank you very much.
