### ISSUE TITLE
Migration from chessboardjsx to react-chessboard

### ISSUE THREAD

**Issue by SuspenseFallback** [Clariity/react-chessboard#24]
This library is really helpful, but I used to use **chessboardjsx** and many of the properties changed, which made migration difficult.

I think that the property names should to match **chessboardjsx**

**Comment by Clariity** [comment]
This project, whilst inspired and adapted from chessboardjsx, should be considered standalone.

I have intentionally changed prop names for them to be more descriptive, alongside adding other props.

It also requires very minimal change to update the prop names when using this package instead of chessboardjsx.
